services:
  mongo:
    image: mongo:7
    container_name: mern-estate-mongo
    restart: unless-stopped
    environment:
       - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: mern-app-api:latest 
    container_name: mern-estate-api
    restart: unless-stopped
    environment:
      - MONGO=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mern-app-client:latest
    container_name: mern-estate-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo-data:
  

    